<a href="https://colab.research.google.com/github/VDidyk/AI/blob/master/module2/%D0%94%D0%97_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Імпортуйте модуль numpy

In [1]:
import numpy as np

#Завдання 1

Створіть масив з парними числами між 30 і 70

In [8]:
print(np.arange(30, 71, 2))

#or

a= np.arange(30,71)
a = a[a % 2 == 0]
print(a)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]
[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


#Завдання 2
Створіть масив з 10 числами між 0(включно) та 1(не включно) див документацію

In [11]:
print(np.random.rand(10))

[0.63581042 0.70038162 0.71161064 0.31110041 0.91095903 0.1299003
 0.51533719 0.62924771 0.47966922 0.95195221]


#Завдання 4
Напишіть функцію яка приймає матрицю розміру nxn та повертає матрицю розміру (n+2) x (n+2), на краях якої розміщенні 0.

In [44]:
def f(m):
  n = m.shape[0]
  a = np.zeros((n+2,n+2), dtype=np.int8)
  a[1:n+1,1:n+1]=m

  return a

n=50
m=np.random.randint(1, 10, size=(n, n), dtype=np.int8)
print(f(m))

int8
[[0 0 0 ... 0 0 0]
 [0 8 7 ... 8 9 0]
 [0 7 8 ... 6 8 0]
 ...
 [0 4 9 ... 4 2 0]
 [0 3 7 ... 9 8 0]
 [0 0 0 ... 0 0 0]]


#Завдання 5
У попередьньому масиві змініть тип даних. Виведіть тип даних до та після зміни

In [47]:
print(m.dtype)
m=m.astype(np.float64)
print(m.dtype)

int8
float64


#Завдання 6
У даному масиві замініть елементи, які дорівнюють\більші\менші за var на -1

In [50]:
x = np.array([1, 5, 3, 8, 6, 5, 7, 4])
var = 5

x[x<var]=-1
x[x==var]=-1
x[x>var]=-1

print(x)

[-1 -1 -1  8  6 -1  7 -1]


#Завдання 7
Замініть пропущені значення матриці(np.nan) на -1

Дивись np.isnan

In [58]:
X = np.array([[1, 2, np.nan, 4],
              [5, np.nan, np.nan, 4],
              [np.nan, 10, 11, np.nan]])

X[np.isnan(X)] = -1
print(X)

[[ 1.  2. -1.  4.]
 [ 5. -1. -1.  4.]
 [-1. 10. 11. -1.]]


#Завдання 8
Створіть матрицю розміру 4х6 з випадковими числами. Змініть її розмір на 3х8

In [67]:
m = np.random.randint(1,10,size=(4,6))
print(m)
m.resize((3,8))
print(m)

[[6 6 4 9 6 3]
 [3 6 5 5 5 9]
 [8 5 2 2 5 2]
 [2 7 5 6 9 5]]
[[6 6 4 9 6 3 3 6]
 [5 5 5 9 8 5 2 2]
 [5 2 2 7 5 6 9 5]]


#Завдання 9
Створіть матрицю з одиниць розміром 3х4. Знайдіть середнє арифметичне(mean) кожного стовпчика

In [76]:
m = np.ones((3,4))
print(np.average(m,axis=0))

[1. 1. 1. 1.]


#Завдання 10
Створіть випадкову матрицю розміром 5х6. Округліть значення до одного знаку після коми(np.round). Розмістіть стовпчики так, щоб значення в першому рядку були відсортовані за зростанням

In [115]:
m = np.random.rand(5,6).round(1)
print(m)
print("--------")
#Це взяв приклад чата GPT. Сподіваюсь що ми ще будемо це проходити тому що наразі це єдине що я не зрозумів.
sorted_indices = m[0, :].argsort()
sorted_m = np.take_along_axis(m, np.expand_dims(sorted_indices, axis=0), axis=1)
print(sorted_m)

[[0.5 1.  0.1 0.2 0.9 0.7]
 [0.  0.4 1.  0.6 0.7 0.9]
 [0.8 0.4 0.3 0.2 0.1 0.7]
 [0.5 0.3 0.1 0.9 0.5 0.7]
 [0.1 0.3 0.1 0.3 0.9 0.3]]
--------
[[0.1 0.2 0.5 0.7 0.9 1. ]
 [1.  0.6 0.  0.9 0.7 0.4]
 [0.3 0.2 0.8 0.7 0.1 0.4]
 [0.1 0.9 0.5 0.7 0.5 0.3]
 [0.1 0.3 0.1 0.3 0.9 0.3]]


#Завдання 11
В даній матриці знайдіть всі елементи зі значенням між 3 і 6

Дивись документацію np.logical_and

In [113]:
X = np.array([[1, 2, 3, 4, 5],
              [6, 7, 8, 9, 10],
              [9, 8, 7, 6, 5],
              [4, 3, 2, 1, 0]])

print(X[(X >= 3) & (X <= 6)])

[3 4 5 6 6 5 4 3]


#Завдання 12
Створіть випадкову матрицю розміру 5х6. Нормалізуйте стовпчики: від кожного елемента ставпчика відніміть мінімальне значення та поділіть результат на різницю між максимальним та мінімальним елементом.

Після цього всі значення мають бути в межах [0, 1]

In [117]:
m = np.random.randint(1,9,size=(5,6))
print(m)
m = (m - np.min(m,axis=0)) / (np.max(m,axis=0) - np.min(m,axis=0))
print(m)

[[8 8 5 7 5 5]
 [7 7 3 7 3 8]
 [2 6 8 6 1 6]
 [5 3 6 7 8 3]
 [2 4 5 8 3 8]]
[[1.         1.         0.4        0.5        0.57142857 0.4       ]
 [0.83333333 0.8        0.         0.5        0.28571429 1.        ]
 [0.         0.6        1.         0.         0.         0.6       ]
 [0.5        0.         0.6        0.5        1.         0.        ]
 [0.         0.2        0.4        1.         0.28571429 1.        ]]
