<a href="https://colab.research.google.com/github/VDidyk/AI/blob/master/module2/%D0%9F%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%BA%D0%B0_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Імпортуйте модуль numpy

In [1]:
import numpy as np;

# Завдання 1
Створіть масив з елементами від 1 до 12. Виведіть розмір та тип масиву

In [3]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# Завдання 2
Зробіть на основі попереднього масиву матрицю з 4 стовчиками. Змініть тип даних матриці на float32. Виведіть транспоновану матрицю.

#Завдання 3
Створіть матрицю 8х8 з 0 та 1 розміщеними в шаховому порядку

In [6]:
a = np.zeros((8, 8), dtype=np.int8)
a[1::2, ::2] = 1
a[::2, 1::2] = 1

a

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]], dtype=int8)

# Завдання 4
Створіть випадкову матрицю 4х3. Знайдіть суму елементів в стовпчиках\рядках\усій матриці

In [15]:
a = np.random.rand(4, 3)
a

array([[0.36066318, 0.26351442, 0.0102769 ],
       [0.03423108, 0.58478567, 0.21981009],
       [0.8955965 , 0.25677596, 0.13033705],
       [0.3195972 , 0.37119621, 0.43147266]])

# Завдання 5
У попередній матриці від кожного рядка відніміть максимальний елемент цього рядка

# Завдання 6
Є дані про вагу контейнерів для перевезення на кораблі: дрібний - 5 т,  малий - 10 т, середній - 25 т, великий - 40 т. На кораблі розміщено 20 дрібних, 5 малих, 10 середніх та 4 великих контейнерів. Знайти масу вантажу.

# Завдання 7
Тепер у нас декілька кораблів. Напишіть код для обчислення вантажу на кожному кораблі.