<a href="https://colab.research.google.com/github/VDidyk/AI/blob/master/module2/%D0%9F%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%BA%D0%B0_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Імпортуйте модуль numpy

In [1]:
import numpy as np;

# Завдання 1
Створіть масив з елементами від 1 до 12. Виведіть розмір та тип масиву

In [3]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# Завдання 2
Зробіть на основі попереднього масиву матрицю з 4 стовчиками. Змініть тип даних матриці на float32. Виведіть транспоновану матрицю.

#Завдання 3
Створіть матрицю 8х8 з 0 та 1 розміщеними в шаховому порядку

In [6]:
a = np.zeros((8, 8), dtype=np.int8)
a[1::2, ::2] = 1
a[::2, 1::2] = 1

a

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]], dtype=int8)

# Завдання 4
Створіть випадкову матрицю 4х3. Знайдіть суму елементів в стовпчиках\рядках\усій матриці

In [14]:
a = np.random.rand(3, 30)
a

array([[0.08664732, 0.90517646, 0.40723842, 0.30728593, 0.28280327,
        0.91518376, 0.36541008, 0.57492632, 0.99905673, 0.9931545 ,
        0.5946783 , 0.65377578, 0.84859762, 0.78315112, 0.28565512,
        0.76402341, 0.20424141, 0.22164062, 0.73068898, 0.54035163,
        0.21402043, 0.22822598, 0.66086273, 0.81502511, 0.39086538,
        0.44390781, 0.91067768, 0.74929996, 0.38761978, 0.30515737],
       [0.67332875, 0.14977534, 0.61000869, 0.53432933, 0.20602924,
        0.80206195, 0.85702783, 0.05201421, 0.33826784, 0.46431208,
        0.98512787, 0.84810801, 0.58393765, 0.77823833, 0.36873208,
        0.73573382, 0.96241079, 0.69956673, 0.43560344, 0.0582246 ,
        0.26609477, 0.05939932, 0.59004348, 0.88805469, 0.2296912 ,
        0.97047543, 0.34368204, 0.58286638, 0.58554738, 0.15327723],
       [0.76191143, 0.51336228, 0.00442747, 0.26797538, 0.9906361 ,
        0.6120722 , 0.58826487, 0.59535577, 0.12075135, 0.189781  ,
        0.70200306, 0.84160789, 0.38122043, 0.

# Завдання 5
У попередній матриці від кожного рядка відніміть максимальний елемент цього рядка

# Завдання 6
Є дані про вагу контейнерів для перевезення на кораблі: дрібний - 5 т,  малий - 10 т, середній - 25 т, великий - 40 т. На кораблі розміщено 20 дрібних, 5 малих, 10 середніх та 4 великих контейнерів. Знайти масу вантажу.

# Завдання 7
Тепер у нас декілька кораблів. Напишіть код для обчислення вантажу на кожному кораблі.