<a href="https://colab.research.google.com/github/VDidyk/AI/blob/master/module4/%D0%9F%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%BA%D0%B0_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Імпорт модулів

In [1]:
import torch
import numpy as np

# Завдання 1

Перегляньте інформацію про доступні процесори, та виведіть про них інформацію

In [3]:
print(torch.cuda.is_available())

if torch.cuda.is_available():
    print(torch.cuda.device_count())
    print(torch.cuda.get_device_name(0))

tensor = torch.tensor([1, 2, 3])
print(tensor.device)

True
1
Tesla T4
cpu


# Завдання 2
Підключіть colab до процесора GPU, та знову виведіть інформацію про доступні процесори

In [6]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

tensor = torch.tensor([1, 2, 3])
tensor = tensor.to(device)

tensor

tensor([1, 2, 3], device='cuda:0')

In [8]:
device

device(type='cuda')

In [9]:
tensor = torch.tensor([1, 2, 3], device=device)
tensor

tensor([1, 2, 3], device='cuda:0')

# Завдання 3
Створіть випадковий тензор розміру (2, 3). Виведіть інформацію про його:

* розмір
* тип даних
* процесор
* наявність градієнта

In [13]:
tensor = torch.randn(2, 3)

print(tensor.shape)
print(tensor.dtype)
print(tensor.device)
print(tensor.requires_grad)

torch.Size([2, 3])
torch.float32
cpu
False


# Завдання 4

Створіть 2 тензора розміру 100. Використовуючи лише модуль `torch` обрахуйте середьню абсолютну похибку(mae) між ними. Виведіть результат як число

In [14]:
tensor1 = torch.rand(100)
tensor2 = torch.rand(100)

mae = torch.abs(tensor1 - tensor2).mean()

print(mae.item())

0.28640586137771606


# Завдання 5

Створіть 3 випадкових тензора з розмірами:
* 32х28х28
* 16х28х28
* 64х28х28

Об'єднайте їх по першій розмірності. Результат має мати розмір 112х28х28

In [15]:
tensor1 = torch.randn(32, 28, 28)
tensor2 = torch.randn(16, 28, 28)
tensor3 = torch.randn(64, 28, 28)

result = torch.cat((tensor1, tensor2, tensor3), dim=0)

print(result)
print(result.size())

tensor([[[-1.5038e+00,  9.7188e-01, -3.5879e-02,  ...,  5.0463e-01,
          -7.4376e-01,  8.6473e-02],
         [-1.8337e-01, -5.3411e-02, -5.8950e-01,  ..., -2.5850e-01,
          -3.6499e-01,  2.2582e-01],
         [-1.0303e+00, -2.7238e-01,  4.1925e-01,  ...,  8.9169e-01,
          -6.8262e-01,  6.7231e-01],
         ...,
         [-4.8050e-01, -1.4293e+00,  7.9768e-01,  ..., -1.1734e+00,
          -6.5780e-01,  1.5847e+00],
         [ 1.6486e-01, -1.5944e+00,  2.9753e+00,  ...,  3.3740e-01,
           6.2203e-01,  4.3243e-01],
         [-2.6246e-01, -6.1189e-01, -7.3341e-02,  ...,  2.2103e+00,
           1.5427e+00, -2.2080e-01]],

        [[ 4.4678e-01,  5.0994e-01,  1.7751e+00,  ..., -4.0205e-02,
          -1.0441e+00, -9.5785e-01],
         [-2.2953e+00, -1.4874e+00, -1.9661e+00,  ...,  4.6245e-01,
           3.9127e-01,  1.1839e+00],
         [-1.0410e+00,  4.6923e-01,  1.7934e+00,  ...,  1.5528e+00,
           6.7990e-01, -7.0237e-01],
         ...,
         [-1.1871e+00,  1

# Завдання 6
Застосуйте метод градієнтного спуску для функції

In [17]:
def f(x):
  return x**2/3 + torch.sin(torch.pi*x)

In [24]:
device = "cuda" if torch.cuda.is_available() else "cpu"
torch.set_default_device(device)


x = torch.tensor(2.0, requires_grad=True)

learning_rate = 1e-3

for t in range(2000):
    loss = f(x)

    loss.backward()

    if t % 100 == 0:
      print(f'{loss.item()=}')

    with torch.no_grad():

      x -= learning_rate*x.grad

      x.grad = None

loss.item()=1.3333334922790527
loss.item()=-0.012307047843933105
loss.item()=-0.26274728775024414
loss.item()=-0.2934073805809021
loss.item()=-0.29722774028778076
loss.item()=-0.29771918058395386
loss.item()=-0.2977832555770874
loss.item()=-0.29779165983200073
loss.item()=-0.29779279232025146
loss.item()=-0.297792911529541
loss.item()=-0.297792911529541
loss.item()=-0.29779303073883057
loss.item()=-0.29779285192489624
loss.item()=-0.29779285192489624
loss.item()=-0.29779285192489624
loss.item()=-0.29779285192489624
loss.item()=-0.29779285192489624
loss.item()=-0.29779285192489624
loss.item()=-0.29779285192489624
loss.item()=-0.29779285192489624


# Завдання 7
Застосуйте метод градієнтного спуску для функції. Мінімум функції рівний 0

In [21]:
def f1(x, y):
  # функція Швефеля
  return  418.9829*2 - x*torch.sin(x.abs().sqrt()) - y*torch.sin(y.abs().sqrt())

def f2(x, y):
  # трьохгорбна функція
  return 2*x**2  - 1.05*x**4 + 1/6*x**6 + x*y  + y**2

def f3(x, y):
  # функція птах
  return 106.7645 + torch.sin(x)*torch.exp((1-torch.cos(y))**2) + \
  torch.cos(y)*torch.exp((1-torch.sin(x))**2) + \
  (x-y)**2

In [54]:
def gr(f, learning_rate=1e-3):
  device = "cuda" if torch.cuda.is_available() else "cpu"
  torch.set_default_device(device)

  x = torch.tensor(6.0, requires_grad=True, device=device)
  y = torch.tensor(6.0, requires_grad=True, device=device)

  for t in range(2000):
      loss = f(x,y)

      loss.backward()

      #if t % 100 == 0:
        #print(f'{loss.item()=}')

      with torch.no_grad():

        x -= learning_rate*x.grad

        x.grad = None

        y -= learning_rate*y.grad

        y.grad = None

  return x.item(), y.item(), loss.item()

In [55]:
gr(f1)

(5.579611778259277, 5.579611778259277, 830.1219482421875)

In [62]:
gr(f2,1e-3)

(-1.757537841796875, 0.9799004793167114, 0.3094998598098755)

In [41]:
gr(f3)

(6.948032379150391, 7.188266277313232, 108.25152587890625)